### ISSUE TITLE
ValueError: Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by qingfengmingyue** [ZZUTK/SRNTT#9]
Traceback (most recent call last):
  File "main.py", line 130, in <module>
    is_original_image=args.is_original_image
  File "/root/SRNTT/SRNTT/model.py", line 925, in test
    network=self.net_upscale) is False:
  File "/root/SRNTT/SRNTT/tensorlayer/files.py", line 722, in load_and_assign_npz
    params = load_npz(name=name)
  File "/root/SRNTT/SRNTT/tensorlayer/files.py", line 634, in load_npz
    return d['params']
  File "/root/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/numpy/lib/format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by WMF1997** [comment]
I think your ```numpy``` version maybe a little higher. 
You can try:
```
pip install numpy==1.16.1
```
if it still not work
```
pip install numpy==1.15.1
```
numpy 1.15.X ?

**Comment by jxingm** [comment]
> I think your `numpy` version maybe a little higher.
> You can try:
> 
> ```
> pip install numpy==1.16.1
> ```
> 
> if it still not work
> 
> ```
> pip install numpy==1.15.1
> ```
> 
> numpy 1.15.X ?
It works.
